name: CI/CD - React to Ubuntu (CRA or Vite, SCP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # working-directory: .   # 프론트가 서브폴더면 경로로 바꿔줘 (예: frontend)

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install deps (lockfile 없으면 npm install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (CRA or Vite)
        run: npm run build
        env:
          CI:false

      - name: Detect build output dir
        id: out
        run: |
          if [ -d dist ]; then echo "DIR=dist" >> $GITHUB_OUTPUT; \
          elif [ -d build ]; then echo "DIR=build" >> $GITHUB_OUTPUT; \
          else echo "No dist or build dir"; exit 1; fi

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Deploy with SCP
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          OUT="${{ steps.out.outputs.DIR }}"
          echo "Uploading $OUT -> $DEPLOY_PATH"
          ssh -i id_rsa -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$DEPLOY_PATH' && rm -rf '$DEPLOY_PATH'/*"
          scp -i id_rsa -P "$SSH_PORT" -r "$OUT"/* "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"
